Starting WiFi connection setup...
[INFO] Ensuring NetworkManager is active...
[INFO] Attempting to connect to the predefined network (YourSSID)...
[ERROR] Could not connect to the predefined network (YourSSID).
[INFO] Scanning available networks...
[INFO] Please enter the number of the network you want to connect to:
[INFO] Enter the password for the network:
[SUCCESS] Successfully connected to SelectedNetwork!
[INFO] Command history has been cleared.
[SECURITY] Removing the script to ensure no traces of the configuration...
[INFO] Configuration complete. The system is ready!
